backend:
  image:
    repository: cloud-secure-back
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
mongo:
  image:
    repository: mongo
    tag: 5.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
