apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-secure-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-secure-back
  template:
    metadata:
      labels:
        app: cloud-secure-back
    spec:
      containers:
        - name: backend
          image: cloud-secure-back:latest
          ports:
            - containerPort: 3000
        - name: mongo
          image: mongo:5.0
          ports:
            - containerPort: 27017
