apiVersion: v1
kind: Service
metadata:
  name: cloud-secure-back
spec:
  selector:
    app: cloud-secure-back
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: cloud-secure-back
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
